export const LOGGEDIN = 'LOGGEDIN';
export const LOGGEDOUT = 'LOGGEDOUT';
export const LOGGEDIN_CHECKING = 'LOGGEDIN_CHECKING';

export const ISADMIN = 'ISADMIN';


export const AUTHERROR = 'AUTHERROR';

export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
